[package]
name = "fractals"
version = "0.1.0"
edition = "2021"
default-run = "mandelbrot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.3"
rayon = "1.10.0"
sdl2 = { version = "0.37", features = ["gfx"] }
