[package]
name = "fractals"
version = "0.1.0"
edition = "2021"
default-run = "mandelbrot"

[dependencies]
num = "0.4.3"
rand = "0.8.5"
rayon = "1.10.0"
sdl2 = { version = "0.37", features = ["gfx"] }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "fractals_bench"
harness = false
